version: "3.8"
services:
  # order
  order-service:
    build: ./order-service
    ports:
      - "8001:8080"
    depends_on:
      - postgres-order-db
  postgres-order-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
  # customer
  customer-service:
    build: ./customer-service
    ports:
      - "8002:8080"
    depends_on:
      - redis-customer-db
  redis-customer-db:
    image: redis
  # product
  product-service:
    build: ./product-service
    ports:
      - "8003:8080"
    depends_on:
      - redis-product-db
  redis-product-db:
    image: redis
