version: "3"
services:
  java-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    container_name: postgres-order-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
